### ISSUE TITLE
Privacy gevoelige gegevens openbaar

### ISSUE THREAD

**Issue by p8** [Oefenweb/cakephp-edexml#14]
Geen idee of deze data echt is of niet maar volgens mij moet je het anonimiseren.
https://github.com/Oefenweb/cakephp-edexml/blob/master/Test/File/EDEXML-1.0.3/sample.xml

**Comment by tersmitten** [comment]
As far as I know this is no real data. I'll make sure to double check. Let me get back to you.

**Comment by tersmitten** [comment]
It's no real data, also see:

* https://www.edustandaard.nl/standaard_afspraken/edexml/edexml-2-0/
* https://www.edustandaard.nl/standaard_afspraken/edexml/edexml-2-1/
